package smartsuite.app.bp.edoc.pdfmaker;

public final class WaterMarkText {
	public static final String FOOTERTEXT_KR = "본 문서는 @org_nm@ 전자계약시스템에서 생성한 문서입니다.\n본 문서에 대한 효력은 계약주체인 양사가 전자서명해야 합니다.\n양사 전자서명 여부는 @org_nm@ 전자계약시스템에서 확인하시기 바랍니다.";
	public static final String FOOTERTEXT_EN = "This document is generated by the @org_nm@ electronic contract system.\nThe validity of this document must be electronically signed by the contracting parties.\nPlease check with the @org_nm@ Electronic Contract System for electronic signature status.";
	public static final String HEADERTEXT_KR = "계약번호 : @cntr_no@";
	public static final String HEADERTEXT_EN = "Contract No : @cntr_no@";
}
